version: '3'

services:
    web:
        # tty: true
        image: python:3.9
        depends_on:
            - db
        volumes:
            - .:/opt/service_for_tests
        container_name: service-for-tests-web
        ports:
            - "0.0.0.0:8001:8000"
        env_file: .env
        working_dir: /opt/service_for_tests
        command: /bin/bash -c 'scripts/run_server.sh'
    db:
        image: postgres:12.0-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        container_name: service-for-tests-db
        env_file: .env
