# Generated by Django 3.2.6 on 2021-08-13 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['user'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Варианты Ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['points'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.ManyToManyField(related_name='answer_options', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ManyToManyField(related_name='correct_answer', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_question', models.IntegerField(editable=False)),
                ('points_earned', models.FloatField(editable=False)),
                ('max_points', models.FloatField(editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'results',
                'ordering': ['user'],
            },
        ),
    ]
