# Generated by Django 3.2.6 on 2021-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210813_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_points', models.FloatField(default=0, editable=False)),
                ('questions', models.ManyToManyField(to='polls.Question')),
            ],
        ),
    ]
