# Generated by Django 3.2.6 on 2021-08-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
    ]
