# Generated by Django 3.2.6 on 2021-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RightChoice',
        ),
    ]
