# Generated by Django 3.2.6 on 2021-08-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210814_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='max_points',
        ),
    ]
