# Generated by Django 3.2.6 on 2021-08-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210815_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='points',
        ),
    ]
